name: Weekly script

on:
  # läuft jeden Donnerstag um 07:00 UTC (Sommer: 09:00 Berlin, Winter: 08:00 Berlin)
  schedule:
    - cron: '0 7 * * 4'
  # optional: manuell auslösbar
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run weekly script
        # Passe den Pfad zu deinem Skript an:
        run: python scraper.py
        # Falls du Secrets brauchst, hier einbinden:
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
